# Basic
title: Zecheng Zhuo
subtitle: IT、投资、学习
welcome_message: <a href="https://zechengzhuo.org" target="_blank">主页</a>
description: 学习学习再学习.
creator: <a href="http://zechengzhuo.org">@zecheng</a>

url: "http://zechengzhuo.org"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
#    disqus: vno-jekyll
layout: default
comments: true
# other options
---
    
# Social
social:
    #weibo: onevcat
    #github: onevcat
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: zhuozch@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
